; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
; platform = atmelavr
board = esp32doit-devkit-v1
; board = megaatmega2560
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_rts = 0
monitor_dtr = 0
monitor_eol = LF
monitor_echo = yes
lib_deps =
	emelianov/modbus-esp8266 @ ^4.1.0

[env:A]
build_type = debug
build_src_filter = 
	+<main.cpp>
lib_deps =
	marcoschwartz/LiquidCrystal_I2C@^1.1.4

; move=80000
; move=20000
; move=-20000


; [env:MasterEsp]
; build_src_filter =
; 	+<master.cpp>


; [env:SlaveEsp]
; build_src_filter =
; 	+<ui.cpp>

; [env:ModbusNetworkTest]
; build_src_filter =
; 	+<modbus_network_test.cpp>

; [env:i2c_scan]
; src_filter =
; 	+<find_i2c_address.cpp>
